### ISSUE TITLE
Have public access?

### ISSUE THREAD

**Issue by mikaelhadler** [labic/hash-web-ng#15]
Hey guys, good nigth.

I can't access clone to this repository, i receive "Permission denied" on the cli, it's possible make this access? :+1:

**Comment by gustavorps** [comment]
Hi @mikaelhadler,
The repository only accept write from the team, but I'm able to clone without problem on a [C9](https://c9.io/) project using the https url. 
My suggestion to you is fork the project at your account and If you are willing, you can send shipping requests, they are welcome!

**Comment by mikaelhadler** [comment]
It's okay for me, I'm going to the fork and trying to learn more about this project, as your suggestion, @GustavoRPS, thanks for that explanation, this is it!
